README.md
só para dizer que contribui rsrs
=> fix: Correção de alguns erros de digitação

README.md
=> fix: ajuste do requestedAt com aspas duplos e texto para melhor entendimento

participantes/luizcordista-go/README.md, participantes/luizcordista-go/docker-compose.yml, participantes/luizcordista-go/info.json, participantes/luizcordista-go/nginx.conf
- **Linguagem:** Go
- **Armazenamento/Fila:** Redis
- **Balanceador:** Nginx
- **Orquestração:** Docker Compose
1. Suba o docker-compose dos Payment Processors primeiro (conforme instruções do repositório oficial).
2. Depois, suba este compose:
```sh
docker compose up --build
```
3. O backend ficará disponível na porta **9999**.
O backend foi desenvolvido em Go, processando pagamentos de forma assíncrona com Redis como fila e armazenamento. O Nginx faz o balanceamento entre as instâncias. O health check dos processadores é respeitado para priorizar o default e só usar o fallback quando necessário.
[https://github.com/LuizCordista/rinha-backend-2025](https://github.com/LuizCordista/rinha-backend-2025)
=> submission LuizCordista

participantes/joaoreisa-go/README.md, participantes/joaoreisa-go/docker-compose.yml, participantes/joaoreisa-go/info.json, participantes/joaoreisa-go/nginx.conf
=> Submissão Rinha - João Victor Reis Alves

participantes/victorverdoodt-cs/README.md, participantes/victorverdoodt-cs/docker-compose.yml, participantes/victorverdoodt-cs/nginx-conf/default.conf, participantes/victorverdoodt-cs/pg-conf/script.sql
=> Submissão Rinha - Victor Verdoodt

participantes/victorverdoodt-cs/README.md, participantes/victorverdoodt-cs/docker-compose.yml
atualização do compose para adicionar healthchecks para meu warmup funcionar
=> Atualização do compose e readme

participantes/lpicanco-rust/README.md, participantes/lpicanco-rust/docker-compose.yml, participantes/lpicanco-rust/info.json
Adicionando minha versão da rinha em Rust
=> adding lpicanco

participantes/joelgarciajr84-go/docker-compose.yml, participantes/joelgarciajr84-go/info.json, participantes/joelgarciajr84-go/nginx/nginx.conf, participantes/joelgarciajr84-go/readme.md, rinha-test/run-tests.sh
Submissão da solução em Go com fallback, retries e Redis.
Participante: Joel Garcia Jr.
Repositório: https://github.com/joelgarciajr84/rinha-backend-go
=> Submissão da solução em Go com fallback, retries e Redis.

participantes/lpicanco-rust/docker-compose.yml
=> chore: update compose file

participantes/bine-rinha-backend-react-php/README.md, participantes/bine-rinha-backend-react-php/docker-compose.yaml, participantes/bine-rinha-backend-react-php/info.json, participantes/bine-rinha-backend-react-php/nginx.conf
=> feat: submissão bine-rinha-backend-react-php

participantes/ricardovhz/README.md, participantes/ricardovhz/docker-compose.yaml, participantes/ricardovhz/info.json, participantes/ricardovhz/nginx.conf
=> Participante ricardovhz

participantes/henriquevalcanaia-swift-vapor/docker-compose.logs, participantes/henriquevalcanaia-swift-vapor/docker-compose.yml
- Adiciona `platform: linux/amd64`.
- Remove `partial-results.json` para nova submissão.
- Remove `docker-compose.logs`
- Remove comentários desnecessários.
---
=> Submissão Henrique Valcanaia - Use `platform: linux/amd64`

participantes/d4vz/docker-compose.yaml, participantes/d4vz/nginx.conf
=> feat: improove api performance and fix nginx issues

participantes/luucaspole-crystal/README.md, participantes/luucaspole-crystal/docker-compose.yaml, participantes/luucaspole-crystal/info.json, participantes/luucaspole-crystal/nginx.conf
=> feat(participantes): add luucaspole

participantes/rodrigo-schonardt-go/README.md, participantes/rodrigo-schonardt-go/docker-compose.yml, participantes/rodrigo-schonardt-go/haproxy.cfg, participantes/rodrigo-schonardt-go/info.json
=> Submissão desafio

participantes/kauan-carvalho-go/.info.json, participantes/kauan-carvalho-go/README.md, participantes/kauan-carvalho-go/docker-compose.yml, participantes/kauan-carvalho-go/nginx.conf
=> feat: adds @KauanCarvalho go project

participantes/alexroza-rs/README.md, participantes/alexroza-rs/docker-compose.yml, participantes/alexroza-rs/info.json, participantes/alexroza-rs/nginx.conf
- [ X] Incluí um README.md com informações sobre minha participação.
- [ X] O arquivo `docker-compose.yml` está na raiz do meu diretório.
- [ X] Não ultrapassei os limites de memória (350MB) e CPU (1.5).
- [ X] Não estou incluindo arquivos desnecessários para a execução do teste no meu pull request tais como código fonte, scripts, e excesso de imagens.
- [ X] Não estou alterando arquivos fora do ou dos meus diretórios de participação.
- [ X] Testei pelo menos o funcionamento básico do `docker-compose.yml`, todos os serviços estão subindo e minha API respondendo na porta 9999.
- [ X] Todas imagens contidas no `docker-compose.yml` funcionam na …
=> backend em rust para rinha 2025

participantes/kauan-carvalho-elixir/.info.json, participantes/kauan-carvalho-elixir/README.md, participantes/kauan-carvalho-elixir/docker-compose.yml, participantes/kauan-carvalho-elixir/nginx.conf
=> feat: adds @KauanCarvalho elixir project

participantes/artschur/README.md
=> fixed readme repo link

participantes/rodrixl/README.md, participantes/rodrixl/docker-compose.yml, participantes/rodrixl/info.json, participantes/rodrixl/nginx/nginx.conf
- [ x] Testei pelo menos o funcionamento básico do `docker-compose.yml`, todos os serviços estão subindo e minha API respondendo na porta 9999.
- [ x] Todas imagens contidas no `docker-compose.yml` funcionam na …
=> Commit para participacao

participantes/not4rt-rustcoroutines/README.md, participantes/not4rt-rustcoroutines/docker-compose.yml, participantes/not4rt-rustcoroutines/info.json
=> Submissão not4rt

participantes/gabxdev-java-1/README.md, participantes/gabxdev-java-1/docker-compose.yml, participantes/gabxdev-java-1/info.json, participantes/gabxdev-java-1/nginx.conf, payment-processor/docker-compose.yml
- [x ] Testei pelo menos o funcionamento básico do `docker-compose.yml`, todos os serviços estão subindo e minha API respondendo na porta 9999.
- [x ] Todas imagens contidas no `docker-compose.yml` funcionam na …
=> JAVA THE BEST

misc/requests/insomnia.yml
Fix de typo do arquivo de collection do insomnia.
=> fix: change typo at request name

participantes/andersongomes001/README.md, participantes/andersongomes001/docker-compose.yaml, participantes/andersongomes001/info.json, participantes/andersongomes001/nginx.conf
=> feat(participantes): add andersongomes001

participantes/wlagent/README.md, participantes/wlagent/docker-compose.yml, participantes/wlagent/info.json, participantes/wlagent/nginx.conf
=> New participant

participantes/ccs1201-01/README.md, participantes/ccs1201-01/docker-compose.yml, participantes/ccs1201-01/info.json, participantes/ccs1201-01/nginx.conf
- [ x] Testei pelo menos o funcionamento básico do `docker-compose.yml`, todos os serviços estão subindo e minha API respondendo na porta 9999.
- [ x] Todas imagens contidas no `docker-compose.yml` funcionam na …
=> Submissão com Java24 | SpringBoot | Redis

participantes/artschur/docker-compose.yml
=> updated previously wrong resources

participantes/andersongomes001/README.md, participantes/andersongomes001/docker-compose.yaml
=> Andersongomes001

participantes/josafaverissimo-java-01/README.md, participantes/josafaverissimo-java-01/docker-compose.yml, participantes/josafaverissimo-java-01/info.json, participantes/josafaverissimo-java-01/nginx.conf
=> chore: josafaverissimo's submission

participantes/luanvictor-node/README.md, participantes/luanvictor-node/docker-compose.yml, participantes/luanvictor-node/info.json, participantes/luanvictor-node/nginx.conf, participantes/luanvictor-node/sql/schema.sql
=> feat: add submissão de Luzin7 com Node.js

participantes/gtiburcio-go/README.md, participantes/gtiburcio-go/docker-compose.yml, participantes/gtiburcio-go/info.json, participantes/gtiburcio-go/nginx.config, participantes/gtiburcio-go/script.sql
=> Add gtiburcio-go as participant

participantes/ricardo-santos/docker-compose.logs
=> Rodar novamente

participantes/davigga-node-2/README.md, participantes/davigga-node-2/docker-compose.yml, participantes/davigga-node-2/info.json, participantes/davigga-node-2/nginx/nginx.conf
Melhor e mais veloz (eu espero)
=> Segunda submissão

participantes/lucasgoveia/README.md, participantes/lucasgoveia/docker-compose.yml, participantes/lucasgoveia/info.json, participantes/lucasgoveia/init.sql, participantes/lucasgoveia/nginx.conf
=> primeira submissão

participantes/zsantana-java-quarkus-v1/README.md, participantes/zsantana-java-quarkus-v1/Resumo.md, participantes/zsantana-java-quarkus-v1/docker-compose.yml, participantes/zsantana-java-quarkus-v1/info.json, participantes/zsantana-java-quarkus-v1/nginx.conf
=> Participação Rinha Backend 2025

participantes/rodrigocaldeira-elixir/docker-compose.yml
Nova imagem que corrige a precisão dos amounts na consulta do summary.
=> Rodar novamente os testes

participantes/luucaspole-crystal/docker-compose.yaml, participantes/luucaspole-crystal/nginx.conf
=> chore(compose): adjust to new image and nginx.conf

participantes/asfernandes-haproxy-mongoose-lmdb/README.md, participantes/asfernandes-haproxy-mongoose-lmdb/config/haproxy.cfg, participantes/asfernandes-haproxy-mongoose-lmdb/docker-compose.yml, participantes/asfernandes-haproxy-mongoose-lmdb/info.json
=> Add asfernandes-haproxy-mongoose-lmdb

participantes/leonardotomas-cs/README.md, participantes/leonardotomas-cs/docker-compose.yml, participantes/leonardotomas-cs/info.json, participantes/leonardotomas-cs/init.sql, participantes/leonardotomas-cs/nginx.conf
=> Submission of leonardotomas-cs

participantes/matheusdojava/docker-compose.logs, participantes/matheusdojava/error.logs
=> Remoção do resultado parcial (quando fiz meu envio esqueci de enviar a imagem pro dockerhub)

participantes/jairoandre-go-v2/README.md, participantes/jairoandre-go-v2/docker-compose.yml, participantes/jairoandre-go-v2/info.json, participantes/jairoandre-go-v2/nginx.conf
=> jairoandre-go-v2 submission

participantes/fhgm-dani-ed/README.md, participantes/fhgm-dani-ed/config/nginx.conf, participantes/fhgm-dani-ed/config/setup.sql, participantes/fhgm-dani-ed/docker-compose.yml, participantes/fhgm-dani-ed/info.json
=> submissão fer, ed e dani

participantes/luanvictor-node/docker-compose.yml
=> fix: retira comando de build e usa image

participantes/anibalferreira-rust/init.sql
=> [fix] Fix docker-compose init.sql

participantes/adrianosilva-go/README.md, participantes/adrianosilva-go/docker-compose.yaml, participantes/adrianosilva-go/info.json, participantes/adrianosilva-go/init.sql, participantes/adrianosilva-go/nginx.conf
=> feat: add sub adriano silva

participantes/rafaspimenta-dotnet/README.md, participantes/rafaspimenta-dotnet/docker-compose.yml, participantes/rafaspimenta-dotnet/info.json, participantes/rafaspimenta-dotnet/init.sql, participantes/rafaspimenta-dotnet/nginx.conf
=> Add rafaspimenta-dotnet as participant

participantes/wiliansimoes-dotnet/README.md, participantes/wiliansimoes-dotnet/docker-compose.yaml, participantes/wiliansimoes-dotnet/info.json, participantes/wiliansimoes-dotnet/nginx.conf
=> Participação da rinha backend 2025

participantes/artschur/docker-compose.yml
=> update version to fix tax issue

participantes/maxsonferovante/docker-compose.yml, participantes/maxsonferovante/info.json, participantes/maxsonferovante/nginx.conf, participantes/maxsonferovante/readme.md
=>  Maxson Almeida - Rinha 2025 - JAVA 24

participantes/artschur/docker-compose.yml
=> changed to new version of image

participantes/jairoandre-go-v2/docker-compose.logs, participantes/jairoandre-go-v2/docker-compose.yml, participantes/jairoandre-go-v2/error.logs
=> jairoandre-go-v2 submission (fix docker-compose.yml)

participantes/alan-silva/README.md, participantes/alan-silva/docker-compose.yml, participantes/alan-silva/info.json
=> Submissão alan-venv

participantes/xandao-php/README.md, participantes/xandao-php/docker-compose.yml, participantes/xandao-php/info.json, participantes/xandao-php/nginx.conf
=> Alexandre Beilner

participantes/Maxel-Uds-quarkus/README.md, participantes/Maxel-Uds-quarkus/docker-compose.yml, participantes/Maxel-Uds-quarkus/info.json, participantes/Maxel-Uds-quarkus/init.sql, participantes/Maxel-Uds-quarkus/nginx.conf
=> Payment Router Quarkus

participantes/francoggm-go/README.md, participantes/francoggm-go/docker-compose.yml, participantes/francoggm-go/info.json, participantes/francoggm-go/nginx.conf
=> feat: francoggm submission

participantes/andersongomes001-go/README.md, participantes/andersongomes001-go/docker-compose.yml, participantes/andersongomes001-go/info.json, participantes/andersongomes001-go/nginx.conf, participantes/andersongomes001/README.md
=> feat: Versão criada em Go

participantes/anibalferreira-rust-2/README.md, participantes/anibalferreira-rust-2/docker-compose.yml, participantes/anibalferreira-rust-2/info.json, participantes/anibalferreira-rust-2/init-db/init-db.sql
=> [feat] New rust project with producer / consumer, redis + pg

participantes/felipefrmelo-rust/README.md, participantes/felipefrmelo-rust/docker-compose.yml, participantes/felipefrmelo-rust/info.json, participantes/felipefrmelo-rust/init.sql, participantes/felipefrmelo-rust/nginx.conf
Rust implementation with Axum, PostgreSQL, Redis and async processing
=> Add felipefrmelo-rust submission

participantes/cgb-go-v1/README.md, participantes/cgb-go-v1/docker-compose.logs, participantes/cgb-go-v1/docker-compose.yml, participantes/cgb-go-v1/error.logs, participantes/cgb-go-v1/info.json, participantes/cgb-go-v1/nginx.conf
=> fix submission cgb-go-v1

participantes/dolphs/Caddyfile, participantes/dolphs/README.md, participantes/dolphs/docker-compose.yml, participantes/dolphs/nginx.conf
=> Improvements on participantes/dolphs

participantes/ronssm-CopiRinhaGo/README.md, participantes/ronssm-CopiRinhaGo/docker-compose.yml, participantes/ronssm-CopiRinhaGo/info.json, participantes/ronssm-CopiRinhaGo/nginx.conf
=> nova submissao

participantes/cgb-go-v2/README.md, participantes/cgb-go-v2/docker-compose.yml, participantes/cgb-go-v2/info.json, participantes/cgb-go-v2/nginx.conf
=> add submission cgb-go-v2

participantes/jvsandrade-rust-mini/docker-compose.yaml, participantes/jvsandrade-rust-mini/info.json, participantes/jvsandrade-rust-mini/nginx.conf, participantes/jvsandrade-rust-mini/readme.md
=> Participando da rinha: jvsandrade

participantes/antooniodev-node/info.json
- [x ] Testei pelo menos o funcionamento básico do `docker-compose.yml`, todos os serviços estão subindo e minha …
=> Atualizando para entrar a submissão

participantes/ricardo-santos/docker-compose.yml, participantes/ricardo-santos/haproxy.cfg
=> change max ports, increase hpa memory

rinha-test/rinha.js
Estou adicionando uma proposta de log que ajuda a identificar as inconsistências quando elas ocorrem. Tem facilitado meu desenvolvimento e acredito que pode ajudar outros.
=> add logs de inconsistencias

participantes/joao-xavier/README.md, participantes/joao-xavier/docker-compose.yml, participantes/joao-xavier/info.json, participantes/joao-xavier/nginx.conf
=> add joao-xavier

participantes/alvesluc-node/README.md, participantes/alvesluc-node/docker-compose.yml, participantes/alvesluc-node/info.json, participantes/alvesluc-node/nginx.conf
=> chore: submit

participantes/dbiagi/error.logs
Pode rodar denovo pfvr? Fiz um fix para corrigir o summary.
=> fix: query string deve ser opcional no /summary

participantes/jonhkr/README.md, participantes/jonhkr/docker-compose.yml, participantes/jonhkr/info.json, participantes/jonhkr/nginx.conf
=> Minha participação

participantes/rodrigo-militao/README.md, participantes/rodrigo-militao/docker-compose.yml, participantes/rodrigo-militao/info.json, participantes/rodrigo-militao/nginx.conf
=> add participant rodrigo-militao

participantes/cristian-s-bun-go-1/README.md, participantes/cristian-s-bun-go-1/docker-compose.yml, participantes/cristian-s-bun-go-1/haproxy.cfg, participantes/cristian-s-bun-go-1/info.json
=> Bun + Go Submit (temp)

participantes/lczago-go/README.md, participantes/lczago-go/docker-compose.yml, participantes/lczago-go/info.json, participantes/lczago-go/nginx.conf
=> add participant lczago-go

participantes/geazi-anc/docker-compose.logs, participantes/geazi-anc/error.logs
=> feat: run tests again

participantes/murilo-guedes-toloni/docker-compose.logs, participantes/murilo-guedes-toloni/error.logs
=> removing logs for new test

participantes/wellington-pacheco/README.md, participantes/wellington-pacheco/docker-compose.yaml, participantes/wellington-pacheco/info.json, participantes/wellington-pacheco/init.sql, participantes/wellington-pacheco/nginx.conf
=> add wellington-pacheco

participantes/adriano-moreira-rs/README.md, participantes/adriano-moreira-rs/docker-compose.yaml, participantes/adriano-moreira-rs/info.json, participantes/adriano-moreira-rs/nginx.conf
Build da versão em rust do participante andersongomes001 do dia 27/07/2025
Com as flags
```Dockerfile
ENV RUSTFLAGS='-C target-cpu=skylake -C target-feature=+sse4.2,+cx16,+rdrand,+rdseed,+aes,+fma,+avx,+avx2,+bmi,+bmi2,+lzcnt,+popcnt'
```
na teoria com essas flags é gerado um binario otimizado para tirar o maximo do processador usado nos testes `Intel i7 7700`,
localmente não consigo medir o ganho real dessa flags porque tenho um processador AMD
espero uma melhora de 2% a 10% no p99
---
- x ] Todas imagens contidas no `docker-compose.yml` funcionam na arquitetura linux/amd64.
*Obs.: Se for uma alteração da sua submissão, você pode remover os …
=> adiciona adriano-moreira-rs

participantes/rafaelpadovezi-dotnet/README.md, participantes/rafaelpadovezi-dotnet/docker-compose.yml, participantes/rafaelpadovezi-dotnet/info.json, participantes/rafaelpadovezi-dotnet/nginx.conf
=> feat(rafaelpadovezi): create dotnet submission

participantes/pedrohsb-python/README.md, participantes/pedrohsb-python/docker-compose.yml, participantes/pedrohsb-python/info.json, participantes/pedrohsb-python/nginx.conf
=> feat: add first version

participantes/antooniodev-node/docker-compose.yaml
=> fix: remove redis volume

participantes/joao-xavier/docker-compose.logs, participantes/joao-xavier/docker-compose.yml, participantes/joao-xavier/error.logs
=> retry: using tagged image

participantes/rodrigo-militao/docker-compose.logs, participantes/rodrigo-militao/error.logs
=> [rodrigo-militao] resubmission

participantes/micheloliveira-com-dotnet-csharp-postgres/README.md, participantes/micheloliveira-com-dotnet-csharp-postgres/docker-compose.yml, participantes/micheloliveira-com-dotnet-csharp-postgres/info.json, participantes/micheloliveira-com-dotnet-csharp-postgres/init.sql, participantes/micheloliveira-com-dotnet-csharp-postgres/nginx.conf
=> feat: Submissão Michel Oliveira

participantes/jjeanjacques10/README.md, participantes/jjeanjacques10/docker-compose.yml, participantes/jjeanjacques10/info.json, participantes/jjeanjacques10/nginx.conf
=> feat: add jjeanjacques10 project

participantes/ricassiocosta-node/README.md, participantes/ricassiocosta-node/docker-compose.yaml, participantes/ricassiocosta-node/info.json, participantes/ricassiocosta-node/nginx.conf
…x configuration, and info.json
=> ricassiocosta-node: submetendo nova solução (v0.1.0)

participantes/guilhermesouza-nodejs/README.md, participantes/guilhermesouza-nodejs/docker-compose.yml, participantes/guilhermesouza-nodejs/info.json, participantes/guilhermesouza-nodejs/nginx.conf
=> feat: guilhermesouza-nodejs submission

participantes/lbattochio-dotnet/README.md, participantes/lbattochio-dotnet/docker-compose.yaml, participantes/lbattochio-dotnet/info.json, participantes/lbattochio-dotnet/init.sql, participantes/lbattochio-dotnet/nginx.conf
=> first submission

participantes/rodrigo-militao/docker-compose.logs, participantes/rodrigo-militao/docker-compose.yml, participantes/rodrigo-militao/error.logs
=> [rodrigo-militao] ajuste docker compose

participantes/ronssm-CopiRinhaGo/docker-compose.logs, participantes/ronssm-CopiRinhaGo/docker-compose.yml, participantes/ronssm-CopiRinhaGo/error.logs
=> fix compose

participantes/flads-php/README.md, participantes/flads-php/docker-compose.yml, participantes/flads-php/info.json, participantes/flads-php/nginx/nginx.conf
=> feat: submit flads-php project

participantes/breno5g/README.md, participantes/breno5g/docker-compose.yml, participantes/breno5g/info.json, participantes/breno5g/nginx.conf
=> Add subscription

participantes/fhgm-dani-ed/docker-compose.yml
=> new docker image

participantes/4emcos-golang/README.md, participantes/4emcos-golang/docker-compose.yaml, participantes/4emcos-golang/info.json, participantes/4emcos-golang/init.sql, participantes/4emcos-golang/nginx.conf
=> add new participant

participantes/svaan1-go/docker-compose.yaml, participantes/svaan1-go/nginx.conf
=> feat: svaan1-go 1.5

participantes/rafaspimenta-dotnet/docker-compose.yml
- [x ] Testei pelo menos o funcionamento básico do `docker-compose.yml`, todos os serviços estão subindo e minha API respondendo na porta 9999.
- [x ] Todas imagens contidas no …
=> retest - rebalance resources

participantes/daniloneto/README.md, participantes/daniloneto/docker-compose.yml, participantes/daniloneto/info.json, participantes/daniloneto/nginx.conf
=> add participante

participantes/joelgarciajr84-go/info.json
=> Run Retest

participantes/wendelmax/README.md, participantes/wendelmax/docker-compose.yml, participantes/wendelmax/info.json, participantes/wendelmax/init.sql, participantes/wendelmax/nginx.conf
=> Adicionando participação wendelmax

participantes/maxsonferovante/docker-compose.yml
- [*] Incluí um README.md com informações sobre minha participação.
- [*] O arquivo `docker-compose.yml` está na raiz do meu diretório.
- [*] Eu não incluí um arquivo `partial-results.json`, `k6.logs` e/ou `docker-compose.logs` no meu PR.
- [*] Não ultrapassei os limites de memória (350MB) e CPU (1.5).
- [*] Não estou incluindo arquivos desnecessários para a execução do teste no meu pull request tais como código fonte, scripts, e excesso de imagens.
- [*] Não estou alterando arquivos fora do ou dos meus diretórios de participação.
- [*] Testei pelo menos o funcionamento básico do `docker-compose.yml`, todos os serviços estão subindo e minha API …
=> Worker Adjustment - Maxson Almeida

participantes/rodrigo-militao/nginx.conf
=> [rodrigo-militao] retest

participantes/marcosmarcolin-php/README.md, participantes/marcosmarcolin-php/docker-compose.yml, participantes/marcosmarcolin-php/info.json, participantes/marcosmarcolin-php/nginx.conf
=> Adicionar participação - PHP

participantes/gabriell915-bun-hono-01/README.md, participantes/gabriell915-bun-hono-01/docker-compose.yml, participantes/gabriell915-bun-hono-01/info.json, participantes/gabriell915-bun-hono-01/nginx.conf
=> Adicionando participação gabriel-bun-hono-01

participantes/arthur-seus-1.0.0/README.md, participantes/arthur-seus-1.0.0/docker-compose.yml, participantes/arthur-seus-1.0.0/haproxy.cfg, participantes/arthur-seus-1.0.0/info.json
=> Adicionando participação arthur-seus-1.0.0

participantes/mpedroni-go/README.md, participantes/mpedroni-go/docker-compose.yml, participantes/mpedroni-go/info.json, participantes/mpedroni-go/init.sql, participantes/mpedroni-go/nginx.conf
=> Adicionando participação mpedroni-go v1.0.0

participantes/luucaspole-crystal/docker-compose.logs, participantes/luucaspole-crystal/docker-compose.yaml, participantes/luucaspole-crystal/error.logs
…
- Removed *.logs and partial-results.json files from participantes/luucaspole-crystal/
- Updated docker-compose.yaml with latest version
- Updated nginx.conf with latest version
- Source SHA: 4c7a0cbe5fdeab8dd3b25bcc16825b0da5b834d5
- Triggered manually via workflow_dispatch
=> chore(participantes/luucaspole-crystal): update submission with latest configuration

participantes/djbrunomonteiro/docker-compose.yml
=> [Submissão] - DJBrunomonteiro 

participantes/djbrunomonteiro/docker-compose.logs, participantes/djbrunomonteiro/error.logs
=> Sincronização com upstream e remoção dos logs antigos

participantes/4emcos-golang/docker-compose.logs, participantes/4emcos-golang/docker-compose.yaml, participantes/4emcos-golang/error.logs
=> rerun impl

participantes/andersonhqds-node/.env, participantes/andersonhqds-node/README.md, participantes/andersonhqds-node/docker-compose.yml, participantes/andersonhqds-node/info.json, participantes/andersonhqds-node/init.sql, participantes/andersonhqds-node/nginx.conf, participantes/andersonhqds-node/rabbitmq.conf
=> feat: Implement backend in nodejs for payment provider

participantes/franklaercio/README.md, participantes/franklaercio/docker-compose.yaml, participantes/franklaercio/info.json, participantes/franklaercio/init.sql, participantes/franklaercio/nginx.conf
=> feat(participants): add franklaercio

participantes/MathausCarvalhoNode/README.md, participantes/MathausCarvalhoNode/docker-compose.yml, participantes/MathausCarvalhoNode/info.json, participantes/MathausCarvalhoNode/nginx.conf
=> MathausCarvalhoNode submission - Node.js 

participantes/gabrieleiro/docker-compose.logs, participantes/gabrieleiro/docker-compose.yml, participantes/gabrieleiro/error.logs
=> Retest e Nova tag nas imagens docker

participantes/chrisx/README.md, participantes/chrisx/docker-compose.yml, participantes/chrisx/info.json, participantes/chrisx/nginx.conf, participantes/chrisx/sql/structure.sql
=> Adds Chris as participant

participantes/lucas-santana/README.md, participantes/lucas-santana/docker-compose.yml, participantes/lucas-santana/info.json, participantes/lucas-santana/lighttpd.conf
=> add lucas-santana

participantes/ViniciusAlexsander-python/README.md, participantes/ViniciusAlexsander-python/docker-compose.yml, participantes/ViniciusAlexsander-python/info.json, participantes/ViniciusAlexsander-python/init.sql, participantes/ViniciusAlexsander-python/nginx.conf
=> Submissão vinicius

participantes/hamilton-golang-mongo-default/README.md, participantes/hamilton-golang-mongo-default/config/nginx.conf, participantes/hamilton-golang-mongo-default/docker-compose.yml, participantes/hamilton-golang-mongo-default/info.json
=> new sub: hamilton

participantes/lucaslimafernandes/README.md, participantes/lucaslimafernandes/docker-compose.yaml, participantes/lucaslimafernandes/info.json, participantes/lucaslimafernandes/nginx.conf
=> feat: suubmissão Lucas Lima Fernandes

participantes/wellington-pacheco-fine-tunning/README.md, participantes/wellington-pacheco-fine-tunning/docker-compose.yaml, participantes/wellington-pacheco-fine-tunning/info.json, participantes/wellington-pacheco-fine-tunning/init.sql, participantes/wellington-pacheco-fine-tunning/nginx.conf
=> fine tunning pg sub

participantes/felipeamorim-rust/README.md, participantes/felipeamorim-rust/docker-compose.yml, participantes/felipeamorim-rust/info.json, participantes/felipeamorim-rust/nginx.conf
=> submissão felipe amorim

participantes/ricassiocosta-node/docker-compose.logs, participantes/ricassiocosta-node/error.logs
=> removing partial results to retest

participantes/jairoandre-kotlin/README.md, participantes/jairoandre-kotlin/docker-compose.yml, participantes/jairoandre-kotlin/info.json, participantes/jairoandre-kotlin/nginx.conf
=> jairoandre kotlin submission

participantes/gabxdev-java-3/README.md, participantes/gabxdev-java-3/docker-compose.yml, participantes/gabxdev-java-3/info.json
=> gabxdevjava01

participantes/david-delta-sierra-go/scripts/init.sql
=> PLUS ULTRA

participantes/Maxel-Uds-quarkus/docker-compose.yml
=> Usando fallback 

participantes/gabxdev-java-4/README.md, participantes/gabxdev-java-4/docker-compose.yml, participantes/gabxdev-java-4/info.json
=> gabxdev javao

participantes/brunosilvadev/README.md, participantes/brunosilvadev/docker-compose.yml, participantes/brunosilvadev/info.json, participantes/brunosilvadev/nginx.conf
=> brunosilvadev-dotnet-submissão-1

participantes/arthur-r-oliveira/README.md, participantes/arthur-r-oliveira/docker-compose.yml, participantes/arthur-r-oliveira/info.json, participantes/arthur-r-oliveira/nginx.conf
=> add participantes/arthur-r-oliveira/

participantes/alanlviana-dotnet-v1/README.md, participantes/alanlviana-dotnet-v1/docker-compose.yml, participantes/alanlviana-dotnet-v1/info.json, participantes/alanlviana-dotnet-v1/nginx/docker-entrypoint.d/set-sock-permissions.sh, participantes/alanlviana-dotnet-v1/nginx/nginx.conf
=> add submissão  alanlviana-dotnet-v1

participantes/lucas-lima/docker-compose.yml, participantes/lucas-lima/info.json
=> FIX: Add image on dockerhub

participantes/igor-gregori-bun-v1/README.md, participantes/igor-gregori-bun-v1/docker-compose.yml, participantes/igor-gregori-bun-v1/info.json, participantes/igor-gregori-bun-v1/nginx.conf
=> feat: participante igor-gregori-bun-v1

participantes/ccs1201-04-java-puro/docker-compose.yml
=> New Version 0.0.6

participantes/lucas-lima/docker-compose.logs, participantes/lucas-lima/error.logs
=> restest: lucas lima

participantes/danielsuhett-golang/docker-compose.logs, participantes/danielsuhett-golang/docker-compose.yaml, participantes/danielsuhett-golang/error.logs, participantes/danielsuhett-golang/haproxy.cfg
=> haproxy please work

participantes/hamilton-golang-redis/docker-compose.logs, participantes/hamilton-golang-redis/docker-compose.yml, participantes/hamilton-golang-redis/error.logs
=> restest hamilton

participantes/flads-php/README.md, participantes/flads-php/info.json
=> feat: update readme

participantes/wesley-frias/README.md, participantes/wesley-frias/docker-compose.yaml, participantes/wesley-frias/info.json, participantes/wesley-frias/nginx.conf
=> Add subscription - PHP

participantes/gabxdev-java-5/README.md, participantes/gabxdev-java-5/docker-compose.yml, participantes/gabxdev-java-5/info.json, participantes/gabxdev-java-6/README.md, participantes/gabxdev-java-6/docker-compose.yml, participantes/gabxdev-java-6/info.json, participantes/gabxdev-java-7/README.md, participantes/gabxdev-java-7/docker-compose.yml, participantes/gabxdev-java-7/info.json
=> gabxdev-java-3

participantes/el_yawd-crab/docker-compose.yml
=> submission(el-yawd): Yet another setup change

participantes/medisco-go/README.md, participantes/medisco-go/docker-compose.yml, participantes/medisco-go/info.json, participantes/medisco-go/nginx.conf
=> Submit code v1

participantes/hamilton-golang-dragonflydb/README.md, participantes/hamilton-golang-dragonflydb/config/nginx.conf, participantes/hamilton-golang-dragonflydb/docker-compose.yml, participantes/hamilton-golang-dragonflydb/info.json
=> new sub: dragonfly

participantes/carlosqsilva-go/README.md, participantes/carlosqsilva-go/docker-compose.yml, participantes/carlosqsilva-go/info.json
=> add carlosqsilva

participantes/murilo-guedes-toloni-undertow/README.md, participantes/murilo-guedes-toloni-undertow/docker-compose.yml, participantes/murilo-guedes-toloni-undertow/info.json
=> Implementacao com lb customizado

participantes/murilo-guedes-toloni-undertow/docker-compose.logs, participantes/murilo-guedes-toloni-undertow/docker-compose.yml, participantes/murilo-guedes-toloni-undertow/error.logs
=> Implementacao com lb customizado fix v2

participantes/lipenvs/README.md, participantes/lipenvs/docker-compose.yml, participantes/lipenvs/info.json, participantes/lipenvs/nginx.conf
=> add lipenvs

participantes/carlos-demarco/README.md, participantes/carlos-demarco/docker-compose.yml, participantes/carlos-demarco/info.json, participantes/carlos-demarco/nginx.conf
=> add submission v1

participantes/mxlange-cpp/README.md, participantes/mxlange-cpp/docker-compose.yml, participantes/mxlange-cpp/info.json, participantes/mxlange-cpp/nginx.conf
=> feat - cpp submission

participantes/felipewaku/README.md, participantes/felipewaku/docker-compose.yml, participantes/felipewaku/info.json, participantes/felipewaku/nginx.conf
=> add submission 1.0.0

participantes/flads-go/README.md, participantes/flads-go/docker-compose.yml, participantes/flads-go/info.json, participantes/flads-go/nginx/nginx.conf
=> submit flads-go project

participantes/fhgm-dani-ed/docker-compose.yml
=> fix new submission

participantes/dudebank-bun/docker-compose.logs, participantes/dudebank-bun/docker-compose.yml, participantes/dudebank-bun/error.logs
=> fix docker service name

participantes/sylviot/docker-compose.logs, participantes/sylviot/docker-compose.yml, participantes/sylviot/error.logs
=> fix build section + remove partial sylviot

participantes/mourishitz-go/README.md, participantes/mourishitz-go/docker-compose.yml, participantes/mourishitz-go/info.json, participantes/mourishitz-go/nginx.conf
=> add mourishitz-go

participantes/andre-lucas-quarkus/README.md, participantes/andre-lucas-quarkus/docker-compose.yml, participantes/andre-lucas-quarkus/info.json
- [ x ] Incluí um README.md com informações sobre minha participação.
- [ x ] O arquivo `docker-compose.yml` está na raiz do meu diretório.
- [ x ] Eu não incluí um arquivo `partial-results.json`, `k6.logs` e/ou `docker-compose.logs` no meu PR.
- [ x ]  Não ultrapassei os limites de memória (350MB) e CPU (1.5).
- [ x ] Não estou incluindo arquivos desnecessários para a execução do teste no meu pull request tais como código fonte, scripts, e excesso de imagens.
- [ x ] Não estou alterando arquivos fora do ou dos meus diretórios de participação.
- [ x ] Testei pelo menos o funcionamento básico do `docker-compose.yml`, todos os serviços estão subindo …
=> Submissao Inicial

participantes/mxlange-ws/README.md, participantes/mxlange-ws/docker-compose.yml, participantes/mxlange-ws/info.json
=> feat - golang websocket, own loadbalancer

participantes/lucas-lima-chaves/docker-compose.logs, participantes/lucas-lima-chaves/docker-compose.yml, participantes/lucas-lima-chaves/error.logs
=> retest:  numero 99999999

participantes/tarcisiozf/README.md, participantes/tarcisiozf/docker-compose.yml, participantes/tarcisiozf/info.json
=> Minha submissão

participantes/wendelllsc/docker-compose.yml
=> Fix: Docker Hub access

participantes/ccs1201-04-java-puro/docker-compose.yml, participantes/ccs1201-05-java-undertow/docker-compose.yml
=> chore: reteste

participantes/krymancer/README.md, participantes/krymancer/docker-compose.yml, participantes/krymancer/info.json, participantes/krymancer/nginx.conf
=> participação krymancer

participantes/hamilton-golang-socket-1/docker-compose.yml
=> restest: hamilton

participantes/rodrigo-militao-v2/README.md, participantes/rodrigo-militao-v2/docker-compose.yml, participantes/rodrigo-militao-v2/info.json, participantes/rodrigo-militao-v2/nginx.conf
=> [rodrigo-militao-v2] submission

participantes/davi64lima-bun/README.md, participantes/davi64lima-bun/docker-compose.yml, participantes/davi64lima-bun/info.json, participantes/davi64lima-bun/nginx.conf
=> davi64lima-bun

participantes/lczago-go/docker-compose.yml
=> feat: new image version

participantes/shell-c#/docker-compose.yml
=> Aumentando batchSize 30 -> 40 [Tentativa ajuste erro inconsistencia]

participantes/pedrohsb-golang/docker-compose.logs, participantes/pedrohsb-golang/docker-compose.yml, participantes/pedrohsb-golang/error.logs
=> test -  agora vai 2.3

participantes/diofeher-full-custom/README.md, participantes/diofeher-full-custom/docker-compose.yml, participantes/diofeher-full-custom/haproxy.cfg, participantes/diofeher-full-custom/info.json, participantes/diofeher-full-custom/pre-processing.lua, participantes/diofeher-full-custom/redis.conf, participantes/diofeher/README.md
=> diofeher: customizando redis e haproxy

participantes/joyce-go/README.md, participantes/joyce-go/docker-compose.yml, participantes/joyce-go/info.json
=> first-test

participantes/developerarthur/README.md, participantes/developerarthur/docker-compose.yaml, participantes/developerarthur/info.json, participantes/developerarthur/init-mydb.sql, participantes/developerarthur/nginx.conf
=> submetendo minha solucao para rinha

participantes/caiqueborges-quarkus/README.md, participantes/caiqueborges-quarkus/docker-compose.yml, participantes/caiqueborges-quarkus/info.json, participantes/caiqueborges-quarkus/nginx.conf
=> Participação - Caique Borges

participantes/rafaelviefe/README.md, participantes/rafaelviefe/docker-compose.yml, participantes/rafaelviefe/info.json, participantes/rafaelviefe/loadbalancer.md, participantes/rafaelvieira/README.md, participantes/rafaelvieira/docker-compose.yml, participantes/rafaelvieira/info.json, participantes/rafaelvieira/loadbalancer.md
=> rafaelviefe submissions

participantes/ccs1201-06-native-pgo/nginx.conf
=> fix: nginx.conf

participantes/4emcos-bun/README.md, participantes/4emcos-bun/devops/handle_requests.lua, participantes/4emcos-bun/devops/nginx.conf, participantes/4emcos-bun/docker-compose.yaml, participantes/4emcos-bun/info.json, participantes/4emcos-bun/init.sql
=> new submission

participantes/uchoamp-zig+nginx/docker-compose.logs, participantes/uchoamp-zig+nginx/error.logs
=> o erro é meu de está usando windows(problema corrigido na imagem)

participantes/marcelo-dias/docker-compose.logs, participantes/marcelo-dias/docker-compose.yml, participantes/marcelo-dias/error.logs, participantes/marcelo-dias/haproxy.cfg
=> Novo teste haproxy

participantes/marcelo-dias/docker-compose.logs, participantes/marcelo-dias/docker-compose.yml, participantes/marcelo-dias/error.logs
=> habilitando todos os logs

participantes/macedot/.env, participantes/macedot/README.md, participantes/macedot/docker-compose.yml, participantes/macedot/haproxy.cfg, participantes/macedot/info.json
=> versao inicial

participantes/Maxel-Uds-quarkus-java-21/README.md, participantes/Maxel-Uds-quarkus-java-21/docker-compose.yml, participantes/Maxel-Uds-quarkus-java-21/info.json, participantes/Maxel-Uds-quarkus/init.sql
=> Usando java 21

participantes/g4brielV-java1/.env, participantes/g4brielV-java1/README.md, participantes/g4brielV-java1/docker-compose.yaml, participantes/g4brielV-java1/info.json, participantes/g4brielV-java1/nginx.conf
=> g4brielV-java-standard

participantes/sylviot/docker-compose.yml, participantes/sylviot/haproxy.cfg
=> new version sylviot

participantes/victorcoelh-python-fastapi/README.md, participantes/victorcoelh-python-fastapi/docker-compose.yml, participantes/victorcoelh-python-fastapi/info.json, participantes/victorcoelh-python-fastapi/nginx.conf
=> victorcoelh - primeira submissão

participantes/tarcisiozf-asm-2/README.md, participantes/tarcisiozf-asm-2/docker-compose.yml, participantes/tarcisiozf-asm-2/info.json, participantes/tarcisiozf-asm-2/nginx.conf
=> paralelizando testes

participantes/camilo-coelho-spring/README.md, participantes/camilo-coelho-spring/docker-compose.yml, participantes/camilo-coelho-spring/info.json, participantes/camilo-coelho-spring/init.sql, participantes/camilo-coelho-spring/nginx.conf
=> submissão spring boot

participantes/danielsuhett-golang/docker-compose.yaml
=> fix my compose

participantes/samuelpanzera-rs-coroutines/docker-compose.yml, participantes/samuelpanzera-rs-coroutines/info.json, participantes/samuelpanzera-rs-coroutines/nginx.conf, participantes/samuelpanzera-rs-coroutines/readme.md
=> Envio de submissão para o desafio

participantes/pru/README.md, participantes/pru/docker-compose.yml, participantes/pru/info.json, participantes/pru/init.sql, participantes/pru/nginx.conf
=> 🐦 pru: a wild pidgeon appears (v1.0.0)

participantes/diogoloff-delphi/README.md, participantes/diogoloff-delphi/docker-compose.yml, participantes/diogoloff-delphi/info.json, participantes/diogoloff-delphi/nginx.conf
=> diogoloff-delphi

participantes/jeifersonalmeida-stage-1/README.md, participantes/jeifersonalmeida-stage-1/docker-compose.yml, participantes/jeifersonalmeida-stage-1/haproxy.cfg, participantes/jeifersonalmeida-stage-1/info.json
=> feat: adiciona submissão jeifersonalmeida-stage-1

participantes/gustavocesario-ktor/README.md, participantes/gustavocesario-ktor/docker-compose.yml, participantes/gustavocesario-ktor/info.json, participantes/gustavocesario-ktor/nginx.conf
=> Submissão Rinha Backend 2025

participantes/hfurlan-java-v1/docker-compose.yaml, participantes/hfurlan-java-v1/sql/ddl.sql
=> Correção no endpoint /payments-summary

participantes/marcelo-dias-skylake-3/README.md, participantes/marcelo-dias-skylake-3/docker-compose.yml, participantes/marcelo-dias-skylake-3/haproxy.cfg, participantes/marcelo-dias-skylake-3/info.json, participantes/marcelo-dias-x86/README.md, participantes/marcelo-dias-x86/docker-compose.yml, participantes/marcelo-dias-x86/haproxy.cfg, participantes/marcelo-dias-x86/info.json
=> Testando skylake de novo

participantes/macedot-go-fasthttp/.env, participantes/macedot-go-fasthttp/README.md, participantes/macedot-go-fasthttp/docker-compose.yml, participantes/macedot-go-fasthttp/haproxy.cfg, participantes/macedot-go-fasthttp/info.json
=> nova solucao: go+fasthttp+socker

participantes/santannaf-java/README.md, participantes/santannaf-java/docker-compose.yml, participantes/santannaf-java/info.json, participantes/santannaf-java/nginx.conf
=> another project

participantes/gldmelo-cs/README.md, participantes/gldmelo-cs/docker-compose.yml, participantes/gldmelo-cs/info.json, participantes/gldmelo-cs/init.sql, participantes/gldmelo-cs/nginx.conf, participantes/gldmelo-cs/postgresql.conf
=> feat: adiciona participante gldmelo

participantes/tarcisiozf-asm-3/README.md, participantes/tarcisiozf-asm-3/docker-compose.yml, participantes/tarcisiozf-asm-3/info.json, participantes/tarcisiozf-asm-3/proxy.cfg
=> retry haproxy

participantes/passos-matheus-only-default/README.md, participantes/passos-matheus-only-default/docker-compose.yml, participantes/passos-matheus-only-default/info.json, participantes/passos-matheus-only-default/nginx.conf
=> feat: testando only default.

participantes/arthur-queiroz-golang/README.md, participantes/arthur-queiroz-golang/docker-compose.yml, participantes/arthur-queiroz-golang/info.json, participantes/arthur-queiroz-golang/init.sql, participantes/arthur-queiroz-golang/nginx.conf
=> sub'meter'

participantes/uchoamp-zig/docker-compose.logs, participantes/uchoamp-zig/error.logs
=> sem erro dessa vez pfv

participantes/thiagorigonatti2-c/README.md, participantes/thiagorigonatti2-c/docker-compose.yml, participantes/thiagorigonatti2-c/haproxy.cfg, participantes/thiagorigonatti2-c/info.json
=> submissão thiagorigonatti#2

participantes/rst77/README.md, participantes/rst77/docker-compose.yml, participantes/rst77/info.json
=> Participação na rinha 2025.

participantes/jorge-java/docker-compose.yml
=> retest:1.3

participantes/kauanborges/README.md, participantes/kauanborges/docker-compose.yml, participantes/kauanborges/info.json, participantes/kauanborges/nginx.conf
=> Kauanborges

participantes/joaoprado-java-spring/README.md, participantes/joaoprado-java-spring/docker-compose.yml, participantes/joaoprado-java-spring/info.json, participantes/joaoprado-java-spring/nginx.conf
=> feat: joaoprado java impl

participantes/chriscorrales/README.md, participantes/chriscorrales/docker-compose.yml, participantes/chriscorrales/info.json, participantes/chriscorrales/nginx.conf
=> Add chriscorrales

participantes/davidalecrim1-go-6/README.md, participantes/davidalecrim1-go-6/config.yaml, participantes/davidalecrim1-go-6/docker-compose.yml, participantes/davidalecrim1-go-6/info.json, participantes/davidalecrim1-go-6/redis.conf
=> add davidalecrim1 versao 6

participantes/leorcvargas-debian-otp28/README.md, participantes/leorcvargas-debian-otp28/docker-compose.yml, participantes/leorcvargas-debian-otp28/info.json, participantes/leorcvargas-debian-otp28/nginx.conf
=> leorcvargas: add version with optimizations, debian and otp28

participantes/leonardosegfault-nodejs/README.md, participantes/leonardosegfault-nodejs/docker-compose.yml, participantes/leonardosegfault-nodejs/info.json, participantes/leonardosegfault-nodejs/nginx.conf
=> Submissão leonardosegfault

participantes/gupers/README.md, participantes/gupers/docker-compose.yml, participantes/gupers/envoy/envoy.yaml, participantes/gupers/info.json, participantes/gupers/init.sql
- [x ] Testei pelo menos o funcionamento básico do `docker-compose.yml`, todos os serviços estão subindo e minha …
=> Gupers submission

participantes/rst77/docker-compose.logs, participantes/rst77/docker-compose.yml, participantes/rst77/error.logs
=> Fix docker-composer. Alteração de referências das imagens.

participantes/White1Lopes/docker-compose.logs, participantes/White1Lopes/docker-compose.yaml, participantes/White1Lopes/error.logs
=> Corrigindo docker compose mal formatado

participantes/josehelioaraujo/README.md, participantes/josehelioaraujo/docker-compose.yml, participantes/josehelioaraujo/info.json, participantes/josehelioaraujo/nginx.conf
=> Add josehelioaraujo

participantes/maxsonferovante-spring-mongo/docker-compose.logs, participantes/maxsonferovante-spring-mongo/docker-compose.yml, participantes/maxsonferovante-spring-mongo/error.logs
=> maxsonferovante spring mongo retest 

participantes/IgorFVicente/docker-compose.yml
=> corrigindo docker-compose para utilizar image corretamente

participantes/gupers/docker-compose.yml
=> fix: docker-compose

participantes/IgorFVicente/docker-compose.logs, participantes/IgorFVicente/error.logs
=> remover logs e partial-result

participantes/fabianoflorentino/config/haproxy.cfg, participantes/fabianoflorentino/docker-compose.logs, participantes/fabianoflorentino/docker-compose.yml, participantes/fabianoflorentino/error.logs, participantes/fabianoflorentino/info.json
=> submissao: corrigindo tag da img v0.0.4 e a falta do info.json

participantes/micheloliveira-com-dotnet-csharp-redis-grpc/README.md, participantes/micheloliveira-com-dotnet-csharp-redis-grpc/docker-compose.yml, participantes/micheloliveira-com-dotnet-csharp-redis-grpc/info.json, participantes/micheloliveira-com-dotnet-csharp-redis-grpc/nginx.conf
=> new sub: micheloliveira-com grpc

participantes/vyctor-nestjs/README.md, participantes/vyctor-nestjs/docker-compose.yml, participantes/vyctor-nestjs/info.json, participantes/vyctor-nestjs/nginx.conf
=> submissao vyctor guimaraes

participantes/murilo-kendjy-node/README.md, participantes/murilo-kendjy-node/conf/nginx.conf, participantes/murilo-kendjy-node/docker-compose.yaml, participantes/murilo-kendjy-node/info.json
=> add murilo-kendjy-node

participantes/yanpitangui-dotnet-v3/README.md, participantes/yanpitangui-dotnet-v3/docker-compose.yml, participantes/yanpitangui-dotnet-v3/info.json, participantes/yanpitangui-dotnet-v3/init.sql, participantes/yanpitangui-dotnet-v3/nginx.conf
=> submissão v3 - envio mais para o default

participantes/marcioendo/README.md, participantes/marcioendo/docker-compose.yml, participantes/marcioendo/info.json
=> add: participante marcioendo

participantes/ba7s-rs/README.md, participantes/ba7s-rs/docker-compose.yml, participantes/ba7s-rs/info.json, participantes/ba7s-rs/nginx.conf
- [ x Testei pelo menos o funcionamento básico do `docker-compose.yml`, todos os serviços estão subindo e minha API respondendo na porta 9999.
=> add participacao matheus

participantes/lecosas-java-spring-graalvm-5/README.md, participantes/lecosas-java-spring-graalvm-5/docker-compose.yaml, participantes/lecosas-java-spring-graalvm-5/info.json, participantes/lecosas-java-spring-graalvm-5/nginx/lua/payments_async.lua, participantes/lecosas-java-spring-graalvm-5/nginx/lualib/http.lua, participantes/lecosas-java-spring-graalvm-5/nginx/lualib/http_connect.lua, participantes/lecosas-java-spring-graalvm-5/nginx/lualib/http_headers.lua, participantes/lecosas-java-spring-graalvm-5/nginx/nginx.conf
=> GraalVM Version 5

participantes/vfabricio-greedy/README.md, participantes/vfabricio-greedy/docker-compose.yml, participantes/vfabricio-greedy/info.json
=> Adicionando vfabricio-greedy

participantes/pedrohsb-golang/docker-compose.yml, participantes/pedrohsb-golang/haproxy.cfg
=> sigo tentando algo

participantes/alansouls-dotnet-aot/README.md, participantes/alansouls-dotnet-aot/docker-compose.yaml, participantes/alansouls-dotnet-aot/info.json, participantes/alansouls-dotnet-aot/nginx.conf
=> add submission for alansouls-dotnet-aot

participantes/alansouls-dotnet-aot/docker-compose.yaml
=> retest alansouls-dotnet-aot - adjust limits

participantes/ba7s-full-rs/README.md, participantes/ba7s-full-rs/docker-compose.yml, participantes/ba7s-full-rs/info.json, participantes/ba7s-full-rs/nginx.conf
=> add participacao matheus v2

participantes/pedrohsb-golang/docker-compose.yml, participantes/pedrohsb-golang/nginx.conf
=> retest - 03:00 AM oq to fazendo da minha vida?

participantes/micheloliveira-com-dotnet-csharp-grpc/README.md, participantes/micheloliveira-com-dotnet-csharp-grpc/docker-compose.yml, participantes/micheloliveira-com-dotnet-csharp-grpc/info.json, participantes/micheloliveira-com-dotnet-csharp-grpc/nginx.conf
=> feat: new sub - micheloliveira-com

participantes/joao-vitor-node/README.md, participantes/joao-vitor-node/createDb.sql, participantes/joao-vitor-node/docker-compose.yml, participantes/joao-vitor-node/haproxy.cfg, participantes/joao-vitor-node/info.json
=> feat: add usuario, minha primeira participação

participantes/santannaf-java-revolts2/README.md, participantes/santannaf-java-revolts2/docker-compose.yml, participantes/santannaf-java-revolts2/info.json, participantes/santannaf-java-revolts2/nginx.conf
=> other code Java- revolts 2

participantes/goulart12-dotnet/README.md, participantes/goulart12-dotnet/docker-compose.yml, participantes/goulart12-dotnet/info.json, participantes/goulart12-dotnet/nginx.conf
=> Goulart12 submission

participantes/rolesosi/README.md, participantes/rolesosi/docker-compose.yaml, participantes/rolesosi/info.json, participantes/rolesosi/nginx.conf
- [x ] Testei pelo menos o funcionamento básico do `docker-compose.yml`, todos os serviços estão subindo e minha …
=> feat: submissão pyhton do rolesosi

participantes/flads-go/README.md, participantes/flads-go/docker-compose.yml, participantes/flads-go/info.json, participantes/flads-go/nginx/nginx.conf
=> feat: submit go project

participantes/gabrielluciano-quarkus/README.md, participantes/gabrielluciano-quarkus/docker-compose.yml, participantes/gabrielluciano-quarkus/info.json, participantes/gabrielluciano-quarkus/nginx.conf
=> feat: submission gabrielluciano

participantes/julipinto-elixir-vanilla/docker-compose.yml, participantes/julipinto-elixir-vanilla/info.json, participantes/julipinto-elixir-vanilla/ngnix.conf, participantes/julipinto-elixir-vanilla/readme.md
=> submission Juliana - Elixir

participantes/passos-matheus-only-default/docker-compose.logs, participantes/passos-matheus-only-default/docker-compose.yml, participantes/passos-matheus-only-default/error.logs, participantes/passos-matheus-python-16reqs-timeout-aptivo/docker-compose.logs, participantes/passos-matheus-python-16reqs-timeout-aptivo/docker-compose.yml, participantes/passos-matheus-python-16reqs-timeout-aptivo/error.logs
- [X ] Não estou incluindo arquivos desnecessários para a execução do teste no meu pull request tais como código fonte, scripts, e excesso de imagens.
=> fix solve images tags.

participantes/juliotsutsui-go/README.md, participantes/juliotsutsui-go/docker-compose.yml, participantes/juliotsutsui-go/info.json, participantes/juliotsutsui-go/initdb/init.sql, participantes/juliotsutsui-go/initdb/postgresql.conf, participantes/juliotsutsui-go/nginx.conf
=> Participação

participantes/pru-async-v2/README.md, participantes/pru-async-v2/docker-compose.yml, participantes/pru-async-v2/info.json, participantes/pru-async-v2/nginx.conf, participantes/pru-async-v2/redis.conf
=> Pru Async V2

participantes/craytee/README.md, participantes/craytee/docker-compose.yml, participantes/craytee/info.json
=> feat: craytee

participantes/eduardompinto-ktor-1/README.md, participantes/eduardompinto-ktor-1/docker-compose.yml, participantes/eduardompinto-ktor-1/info.json, participantes/eduardompinto-ktor-1/nginx.conf
=> Add: eduardompinto-ktor-1

participantes/pru-async-v5/README.md, participantes/pru-async-v5/docker-compose.yml, participantes/pru-async-v5/info.json, participantes/pru-async-v5/nginx.conf, participantes/pru-async-v5/redis.conf
=> new try agressive timeout

participantes/dinossauro/README.md, participantes/dinossauro/config/nginx.conf, participantes/dinossauro/docker-compose.yml, participantes/dinossauro/info.json, participantes/dinossauro/init.sql
=> um dinossauro entrou pra rinha

participantes/dearrudam_java_01/README.md, participantes/dearrudam_java_01/docker-compose.yml, participantes/dearrudam_java_01/info.json, participantes/dearrudam_java_01/nginx.conf
=> Primeira submissão: dearrudam

participantes/igor-lucas-csharp2/docker-compose.logs, participantes/igor-lucas-csharp2/error.logs
=> Altera visibilidade de imagens

participantes/davidalecrim1-go-3/README.md, participantes/davidalecrim1-go-4/README.md, participantes/davidalecrim1-go-5/README.md, participantes/davidalecrim1-go-6/README.md
=> add explicacao do lb customizado para clareza na avaliacao

participantes/joaofsilva-php-swoole/README.md, participantes/joaofsilva-php-swoole/docker-compose.yml, participantes/joaofsilva-php-swoole/info.json, participantes/joaofsilva-php-swoole/nginx.conf
=> solicitação de participação

participantes/micheloliveira-com-dotnet-csharp-postgres-haproxy/README.md, participantes/micheloliveira-com-dotnet-csharp-postgres-haproxy/docker-compose.yml, participantes/micheloliveira-com-dotnet-csharp-postgres-haproxy/haproxy.cfg, participantes/micheloliveira-com-dotnet-csharp-postgres-haproxy/info.json, participantes/micheloliveira-com-dotnet-csharp-postgres-haproxy/init.sql, participantes/micheloliveira-com-dotnet-csharp-postgres/README.md
=> feat: new haproxy postgres sub + compose fix

participantes/wesleymatosdev-rust/docker-compose.yml
a memória estava setado pro limite de 250 na última, nao 350! mb xD
=> wesleymatosdev rust submission

participantes/ogabriel-ruby-rage/README.md, participantes/ogabriel-ruby-rage/docker-compose.yml, participantes/ogabriel-ruby-rage/haproxy.cfg, participantes/ogabriel-ruby-rage/info.json
=> feat: add ogabriel-ruby-rage entry

participantes/adryan1928-fastapi/README.md, participantes/adryan1928-fastapi/docker-compose.yaml, participantes/adryan1928-fastapi/info.json, participantes/adryan1928-fastapi/nginx.conf
=> Add: adryan1928-fastapi

participantes/Gabriel-Golang/Readme.md, participantes/Gabriel-Golang/docker-compose.yml, participantes/Gabriel-Golang/info.json, participantes/Gabriel-Golang/nginx/default.conf
=> Adiciona minha participação de Gabriel na rinha

participantes/jpgo/README.md, participantes/jpgo/docker-compose.yml, participantes/jpgo/info.json, participantes/jpgo/nginx.conf
=> participacao jpgo

participantes/gdx64-rs-uds/docker-compose.yml, participantes/gdx64-rs-uds/info.json, participantes/gdx64-rs-uds/readme.md
=> Gdx64: using uds websockets
